# -*- coding: utf-8 -*-
"""08ex_algebra.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jyFxIGB0Bf7lMDOQmPGljpex5y1BdGZK

1\. **PCA on 3D dataset**

* Generate a dataset simulating 3 features, each with N entries (N being ${\cal O}(1000)$). Each feature is made by random numbers generated according the normal distribution $N(\mu,\sigma)$ with mean $\mu_i$ and standard deviation $\sigma_i$, with $i=1, 2, 3$. Generate the 3 variables $x_{i}$ such that:
    * $x_1$ is distributed as $N(0,1)$
    * $x_2$ is distributed as $x_1+N(0,3)$
    * $x_3$ is given by $2x_1+x_2$
* Find the eigenvectors and eigenvalues using the eigendecomposition of the covariance matrix
* Find the eigenvectors and eigenvalues using the SVD. Check that the two procedures yield to same result
* What percent of the total dataset's variability is explained by the principal components? Given how the dataset was constructed, do these make sense? Reduce the dimensionality of the system so that at least 99% of the total variability is retained
* Redefine the data according to the new basis from the PCA
* Plot the data, in both the original and the new basis. The figure should have 2 rows (the original and the new basis) and 3 columns (the $[x_0, x_1]$, $[x_0, x_2]$ and $[x_1, x_2]$ projections) of scatter plots.
"""

#Create Data
import matplotlib.pyplot as plt

from scipy import linalg as la
from matplotlib import pyplot as plt
import numpy as np
n = 1000

x1 = np.random.normal(0, 1, n).T
x2 = (np.random.normal(0, 3, n) +x1).T
x3 = (2*x1+x2).T
X = np.array([x1, x2, x3]).T
X



###eigenvectors and eigenvalues
#using the eigendecomposition of the covariance matrix

#mean
M = np.mean(X.T, axis=1)
# center columns by subtracting column means
C = X - M
#print(C)
# calculate covariance matrix of centered matrix
cov = np.cov(C.T)
print("Covariance matrix:\n", cov, '\n')

# now find the eigenvectors of the covariance matrix
l, V = la.eig(cov)
# take only the real component, if possible
l = np.real_if_close(l)

print("Eigenvalues:\n", l, '\n')
print("Eigenvectors:\n", V, '\n')

# Check that V is actually an orthogonal matrix (and thus its transpose is also its inverse)
print("VV^T:\n", V.dot(V.T), '\n')

U, s, VT = la.svd(X)
# create m x n Sigma matrix
print("Covariance matrix:\n", VT, '\n')
print("Eigenvalues:\n", s, '\n')
print("Eigenvectors:\n", U, '\n')



import matplotlib.pyplot as plt

from mpl_toolkits.mplot3d import Axes3D

xs = x1

ys = x2

zs = x3

fig = plt.figure()

ax = fig.add_subplot(111, projection='3d')

ax.scatter(xs,ys,zs)

plt.show()

"""2\. **PCA on a nD dataset**

* Start from the dataset you have genereted in the previous exercise and add uncorrelated random noise. Such noise should be represented by other 10 uncorrelated variables normally distributed, with a standard deviation much smaller (e.g. a factor 20) than those used to generate the $x_1$ and $x_2$. Repeat the PCA procedure and compare the results with what you have obtained before.
"""



# Add 10 noisy variables
noises = list(range(10))
for i in range(10):
    noises[i] = np.random.normal(0, 1/20 , 1000)

x = np.vstack([xs, noises])

#PCA
cov = np.cov(x)
l, V = la.eig(cov)
l = np.real_if_close(l)

# Reducing dimensionality of the system
c01 = (np.sum(l[:-1])*100/np.sum(l))
c0 = (np.sum(l[0])*100/np.sum(l))
print("\nPercent of the total variability dataset of component 0 and 1 is ", c01, "%,", "and component 0 is ", c0, "%")

"""3\. **Optional**: **PCA on the MAGIC dataset**

Perform a PCA on the magic04.data dataset.
"""

# get the dataset and its description on the proper data directory
#!wget https://archive.ics.uci.edu/ml/machine-learning-databases/magic/magic04.data -P data/
#!wget https://archive.ics.uci.edu/ml/machine-learning-databases/magic/magic04.names -P data/

